name: '🌃 Nightly'

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: '0 12 * * *'
  workflow_dispatch:

jobs:
  stat:
    if: github.repository_owner == 'abereghici'
    runs-on: ubuntu-latest
    steps:
      - name: Check out code using Git
        uses: actions/checkout@v2
      - name: Set Node version to 16
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install --frozen-lockfile --ignore-engines --ignore-scripts
      - name: Collect stats
        run: node scripts/stats/index.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: '[ci] collect stats'
          branch: ${{ github.head_ref }}

  lockfile:
    if: github.repository_owner == 'abereghici'
    runs-on: ubuntu-latest
    steps:
      - name: Check out code using Git
        uses: actions/checkout@v2

      - name: Set Node version to 16
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'yarn'

      - name: Clear lockfile
        run: rm -rf yarn.lock node_modules

      - name: Install dependencies
        run: yarn install --ignore-engines --ignore-scripts

      - name: Create Pull Request
        id: createpr
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: '[ci] update lockfile'
          title: '[ci] update lockfile'
          body: >
            This PR is auto-generated by a nightly GitHub action.  It should
            automatically be merged if tests pass.

      - name: Mark Pull Request for Auto-Merge
        if: steps.createpr.outputs.pull-request-operation == 'created'
        uses: peter-evans/enable-pull-request-automerge@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{ steps.createpr.outputs.pull-request-number }}
          merge-method: squash
